### ISSUE TITLE
JavaScriptのファイル連携エラーについて

### ISSUE THREAD

**Issue by Hamumayo55** [Hamumayo55/Sukuramukun#11]
## 概要  
javascript_include_tagを入れると, すべてのhtml.erbファイルにjsが紐空いてしまい、idの参照ができないとエラーが起きてしまう.

## 起こった問題  
タイマーが反応しなかったり, ホームのボタンが反応しないことがある.

## 理想として  
html.erbファイルとjsファイルが1つ1つに対応してほしい.

**Comment by hogehiga** [comment]
このへんでなんとかならないでしょうか。

https://railsguides.jp/asset_pipeline.html#%E3%82%B3%E3%83%B3%E3%83%88%E3%83%AD%E3%83%BC%E3%83%A9%E5%9B%BA%E6%9C%89%E3%81%AE%E3%82%A2%E3%82%BB%E3%83%83%E3%83%88

**Comment by hogehiga** [comment]
直ったんですか？
