### ISSUE TITLE
アクセストークンの取り扱い方について

### ISSUE THREAD

**Issue by ksudate** [Hamumayo55/Sukuramukun#12]
外部サービスの認証の際に取得したアクセストークンについて、そのアクセストークンはCookie（例：sessin[:access_token]）に保存していいのでしょうか？
それとも、DBに保存して管理したほうがいいのでしょうか？

**Comment by hogehiga** [comment]
dbです。

理由はここに書いてあります。
https://railsguides.jp/security.html#%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3%E3%82%B9%E3%83%88%E3%83%AC%E3%83%BC%E3%82%B8

**Comment by ksudate** [comment]
ありがとうございます。
理解できました。
